window.portfolioImages = [
  { src: 'trabalhos/grua_1.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/grua_2.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/grua_3.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/grua_4.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/grua_5.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/grua_6.webp', category: 'grua', alt: 'Trabalho de Elevação com Grua - EHS' },
  { src: 'trabalhos/ac_interior_1.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_2.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_3.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_4.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_5.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_6.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_7.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_8.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_9.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_10.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_11.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_12.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_13.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_14.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_15.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_16.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_interior_17.webp', category: 'ac-interior', alt: 'Instalação de Ar Condicionado (Interior) - EHS' },
  { src: 'trabalhos/ac_exterior_1.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_2.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_3.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_4.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_5.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_6.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_7.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_8.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_9.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/ac_exterior_10.webp', category: 'ac-exterior', alt: 'Instalação de Ar Condicionado (Unidade Exterior) - EHS' },
  { src: 'trabalhos/solar_1.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_2.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_3.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_4.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_5.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_6.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_7.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_8.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_9.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/solar_10.webp', category: 'solar', alt: 'Instalação de Painel Solar e Transição Energética - EHS' },
  { src: 'trabalhos/tecnica_1.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_2.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_3.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_4.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_5.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_6.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
  { src: 'trabalhos/tecnica_7.webp', category: 'tecnica', alt: 'Instalação em Sala Técnica Premium - EHS' },
];
